//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowerTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int id_meet { get; set; }
        public string meetDate { get; set; }
        public string meetTime { get; set; }
        public string meetPlace { get; set; }
        public string meetName { get; set; }
        public string meetTheme { get; set; }
        public string meetLeader { get; set; }
    }
}
