//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowerTest.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowerEntities : DbContext
    {
        public FlowerEntities()
            : base("name=FlowerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupPpl> GroupPpl { get; set; }
        public virtual DbSet<Meeting> Meeting { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<userAbout> userAbout { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
