//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowerTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id_prod { get; set; }
        public string nameOfProd { get; set; }
        public Nullable<int> price { get; set; }
        public string sellerPhone { get; set; }
        public Nullable<int> amount { get; set; }
        public string about { get; set; }
    }
}
