//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flowerTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userAbout
    {
        public int id_userAbout { get; set; }
        public Nullable<int> user_id { get; set; }
        public string lastName { get; set; }
        public string secondName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public Nullable<int> group_id { get; set; }
        public string sex { get; set; }
    
        public virtual GroupPpl GroupPpl { get; set; }
        public virtual Users Users { get; set; }
    }
}
